<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Service\VeryBadDesign' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/src/Service/VeryBadDesign.php';

$this->services['App\\Service\\VeryBadDesign'] = $instance = new \App\Service\VeryBadDesign();

$instance->setContainer($this);

return $instance;
