<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Command\HelloCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/HelloCommand.php';

return $this->services['App\\Command\\HelloCommand'] = new \App\Command\HelloCommand(($this->services['App\\Service\\Greeting'] ?? $this->load('getGreetingService.php')));
